### ISSUE TITLE
Microsoft Visual C++ 2015 Redistributable

### ISSUE THREAD

**Issue by NineNein** [paulscherrerinstitute/pcaspy#39]
Maybe its written somwhere and i oversaw it, but
if in the docs it would be mentioned that you need to install the
Microsoft Visual C++ 2015 Redistributable it would helped me :)

**Comment by xiaoqiangwang** [comment]
I expect the 2015 redistributable is installed with Python3.5+. Is this not the case?

**Comment by NineNein** [comment]
I had problems with cpython 3.5 and 3.6, maybe i miss a option at the installation ?!
But since i installed them with the standart settings, i guess is still worth mentioning it.

**Comment by xiaoqiangwang** [comment]
Commit bb9cc00 adds notes about missing redistributable.

**Comment by piuupiuupiuu** [comment]
Had the same problem, this was the error message back than:

Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\pcaspy\cas.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\door\Desktop\pyepics_test\test_server.py", line 3, in <module>
    from pcaspy import SimpleServer, Driver
  File "C:\Program Files\Python35\lib\site-packages\pcaspy\__init__.py", line 1, in <module>
    from .driver import Driver, SimpleServer, PVInfo, SimplePV
  File "C:\Program Files\Python35\lib\site-packages\pcaspy\driver.py", line 1, in <module>
    from . import cas
  File "C:\Program Files\Python35\lib\site-packages\pcaspy\cas.py", line 21, in <module>
    _cas = swig_import_helper()
  File "C:\Program Files\Python35\lib\site-packages\pcaspy\cas.py", line 20, in swig_import_helper
    return importlib.import_module('_cas')
  File "C:\Program Files\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_cas'
